# Generated by Django 4.0.1 on 2022-03-24 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo_Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Perfil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo_TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoDocumento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroDocumento', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('id_Perfiles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.catalogo_perfiles')),
                ('id_TipoDocumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.catalogo_tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Fin', models.DateField()),
                ('Supervisora', models.CharField(max_length=100)),
                ('horasMensualFormacion', models.IntegerField(null=True)),
                ('id_Instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.instructores')),
            ],
        ),
    ]
