# Generated by Django 4.0.1 on 2022-04-02 15:23

import asistenteHorarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructores',
            name='id_TipoDocumento',
        ),
        migrations.AddField(
            model_name='instructores',
            name='TipoDocumento',
            field=models.CharField(choices=[(asistenteHorarios.models.CedulaChoice['CC'], 'Cédula de ciudadanía'), (asistenteHorarios.models.CedulaChoice['CE'], 'Cédula de extranjería')], default='CC', max_length=2),
        ),
    ]
